Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE)values(101,'SNAP','Approved',100,'2022-05-13','2022-05-30');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE)values(102,'SNAP','Approved',100,'2022-05-13','2022-05-30');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,DENEIL_REASON)values(103,'SNAP','Denied','High salary income');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,DENEIL_REASON)values(104,'SNAP','Denied','High rent income');


Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE)values(105,'CCAP','Approved',100,'2022-05-13','2022-05-30');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE)values(106,'CCAP','Approved',100,'2022-05-13','2022-05-30');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,DENEIL_REASON)values(107,'CCAP','Denied','kids not Available');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,DENEIL_REASON)values(108,'CCAP','Denied','kids Age above 16 years');

Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE)values(109,'Medicied','Approved',100,'2022-05-13','2022-05-30');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE)values(110,'Medicied','Approved',100,'2022-05-13','2022-05-30');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,DENEIL_REASON)values(111,'Medicied','Denied','High Income');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,DENEIL_REASON)values(112,'Medicied','Denied','High Property income');

Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE)values(113,'Medicare','Approved',100,'2022-05-13','2022-05-30');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE)values(114,'Medicare','Approved',100,'2022-05-13','2022-05-30');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,DENEIL_REASON)values(115,'Medicare','Denied','High Income');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,DENEIL_REASON)values(116,'Medicare','Denied','Age not Match'); 

Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE)values(117,'QHP','Approved',100,'2022-05-13','2022-05-30');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE)values(118,'QHP','Approved',100,'2022-05-13','2022-05-30');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,DENEIL_REASON)values(119,'QHP','Denied','expird');
Insert Into ELIGIBILITY_DTLS(ELIG_ID,PLAN_NAME,PLAN_STATUS,DENEIL_REASON)values(120,'QHP','Denied','expird'); 